# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\File_Search.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 748)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/control/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.treeView = QtWidgets.QTreeView(Form)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 625, 748))
        self.treeView.setObjectName("treeView")
        self.treeView.header().setCascadingSectionResizes(True)
        self.treeView.header().setDefaultSectionSize(200)
        self.treeView.header().setHighlightSections(True)
        self.treeView.header().setMinimumSectionSize(100)
        self.treeView.header().setSortIndicatorShown(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "文件选择"))
import res_rc
