# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_passage\info\info\Box\UI\info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_info(object):
    def setupUi(self, info):
        info.setObjectName("info")
        info.resize(1358, 875)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/windows/Enroll.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        info.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(info)
        self.label.setGeometry(QtCore.QRect(0, 0, 1681, 881))
        self.label.setStyleSheet("background-color:#21252b;\n"
"border:none;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(info)
        self.textBrowser.setGeometry(QtCore.QRect(0, 50, 1361, 821))
        self.textBrowser.setStyleSheet("border:none;\n"
"color:#fff;\n"
"background-color: transparent;")
        self.textBrowser.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(info)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1361, 41))
        self.widget.setStyleSheet("background-color: #1c2223;")
        self.widget.setObjectName("widget")
        self.exit_2 = QtWidgets.QPushButton(self.widget)
        self.exit_2.setGeometry(QtCore.QRect(1310, 10, 24, 24))
        self.exit_2.setMinimumSize(QtCore.QSize(24, 24))
        self.exit_2.setMaximumSize(QtCore.QSize(24, 24))
        self.exit_2.setStyleSheet("background-color:transparent ;\n"
"border:none;")
        self.exit_2.setObjectName("exit_2")
        self.exit = QtWidgets.QPushButton(self.widget)
        self.exit.setGeometry(QtCore.QRect(1330, 10, 24, 24))
        self.exit.setMinimumSize(QtCore.QSize(24, 24))
        self.exit.setMaximumSize(QtCore.QSize(24, 24))
        self.exit.setStyleSheet("background-color:transparent ;\n"
"border:none;")
        self.exit.setObjectName("exit")
        self.line = QtWidgets.QFrame(info)
        self.line.setGeometry(QtCore.QRect(0, 36, 1851, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(info)
        QtCore.QMetaObject.connectSlotsByName(info)

    def retranslateUi(self, info):
        _translate = QtCore.QCoreApplication.translate
        info.setWindowTitle(_translate("info", "信息"))
        self.exit_2.setText(_translate("info", "➖"))
        self.exit_2.setShortcut(_translate("info", "Esc"))
        self.exit.setText(_translate("info", "❌"))
        self.exit.setShortcut(_translate("info", "Esc"))
import res_rc
