# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_passage\info\info\Box\UI\more_info_.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 487)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/windows/Text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 50, 511, 171))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 18px")
        self.widget.setObjectName("widget")
        self.textBrowser_ex = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_ex.setGeometry(QtCore.QRect(10, 30, 491, 141))
        self.textBrowser_ex.setObjectName("textBrowser_ex")
        self.label_voics = QtWidgets.QLabel(self.widget)
        self.label_voics.setGeometry(QtCore.QRect(10, 0, 161, 31))
        self.label_voics.setStyleSheet("")
        self.label_voics.setObjectName("label_voics")
        self.label_voics.raise_()
        self.textBrowser_ex.raise_()
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(10, 230, 511, 241))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 18px")
        self.widget_2.setObjectName("widget_2")
        self.label_trs = QtWidgets.QLabel(self.widget_2)
        self.label_trs.setGeometry(QtCore.QRect(10, 0, 231, 31))
        self.label_trs.setStyleSheet("")
        self.label_trs.setObjectName("label_trs")
        self.english_tr = QtWidgets.QTextBrowser(self.widget_2)
        self.english_tr.setGeometry(QtCore.QRect(10, 30, 491, 211))
        self.english_tr.setObjectName("english_tr")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 10, 71, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.WindowsTitle = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.WindowsTitle.setContentsMargins(0, 0, 0, 0)
        self.WindowsTitle.setObjectName("WindowsTitle")
        self.small = QtWidgets.QPushButton(self.layoutWidget)
        self.small.setMinimumSize(QtCore.QSize(24, 24))
        self.small.setMaximumSize(QtCore.QSize(24, 24))
        self.small.setStyleSheet("border-radius:12;\n"
"background-color: yellow;")
        self.small.setText("")
        self.small.setObjectName("small")
        self.WindowsTitle.addWidget(self.small)
        self.exit = QtWidgets.QPushButton(self.layoutWidget)
        self.exit.setMinimumSize(QtCore.QSize(24, 24))
        self.exit.setMaximumSize(QtCore.QSize(24, 24))
        self.exit.setStyleSheet("border-radius:12;\n"
"background-color: red;")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.WindowsTitle.addWidget(self.exit)
        self.Background = QtWidgets.QLabel(Dialog)
        self.Background.setGeometry(QtCore.QRect(0, 0, 535, 487))
        self.Background.setStyleSheet("background-color:#363b40;\n"
"border-radius:10px;")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.Background.raise_()
        self.widget.raise_()
        self.widget_2.raise_()
        self.layoutWidget.raise_()
        self.label_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "more_infos"))
        self.textBrowser_ex.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_voics.setText(_translate("Dialog", "Voice changes"))
        self.label_trs.setText(_translate("Dialog", "English translation"))
        self.exit.setShortcut(_translate("Dialog", "Esc"))
        self.label_4.setText(_translate("Dialog", "Details"))
import res_rc
