# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_passage\info\info\Box\UI\MUSIC.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MUSIC_PL(object):
    def setupUi(self, MUSIC_PL):
        MUSIC_PL.setObjectName("MUSIC_PL")
        MUSIC_PL.resize(537, 290)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/English_tools/music_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MUSIC_PL.setWindowIcon(icon)
        MUSIC_PL.setStyleSheet("font: 11pt \"黑体\";\n"
"color:#fff;")
        self.stop = QtWidgets.QToolButton(MUSIC_PL)
        self.stop.setGeometry(QtCore.QRect(240, 250, 41, 31))
        self.stop.setStyleSheet("background-color:transparent;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/windows/play_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon1)
        self.stop.setIconSize(QtCore.QSize(30, 30))
        self.stop.setObjectName("stop")
        self.graphicsView = QtWidgets.QGraphicsView(MUSIC_PL)
        self.graphicsView.setGeometry(QtCore.QRect(235, 30, 300, 200))
        self.graphicsView.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView.setObjectName("graphicsView")
        self.listWidget = QtWidgets.QListWidget(MUSIC_PL)
        self.listWidget.setGeometry(QtCore.QRect(0, 30, 231, 201))
        self.listWidget.setStyleSheet("border:none;\n"
"background-color: #21252b;")
        self.listWidget.setObjectName("listWidget")
        self.dir = QtWidgets.QToolButton(MUSIC_PL)
        self.dir.setGeometry(QtCore.QRect(204, 231, 30, 29))
        self.dir.setStyleSheet("background-color:transparent;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/control/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dir.setIcon(icon2)
        self.dir.setObjectName("dir")
        self.label = QtWidgets.QLabel(MUSIC_PL)
        self.label.setGeometry(QtCore.QRect(161, 237, 36, 18))
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(MUSIC_PL)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 541, 291))
        self.label_12.setStyleSheet("background-color: rgb(28, 34, 35);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.background = QtWidgets.QWidget(MUSIC_PL)
        self.background.setGeometry(QtCore.QRect(0, 0, 541, 31))
        self.background.setStyleSheet("background-color: rgb(31, 31, 31);\n"
"")
        self.background.setObjectName("background")
        self.exit = QtWidgets.QPushButton(self.background)
        self.exit.setGeometry(QtCore.QRect(510, 0, 24, 24))
        self.exit.setMinimumSize(QtCore.QSize(24, 24))
        self.exit.setMaximumSize(QtCore.QSize(24, 24))
        self.exit.setStyleSheet("background-color:transparent ;\n"
"border:none;")
        self.exit.setObjectName("exit")
        self.exit_2 = QtWidgets.QPushButton(self.background)
        self.exit_2.setGeometry(QtCore.QRect(490, 0, 24, 24))
        self.exit_2.setMinimumSize(QtCore.QSize(24, 24))
        self.exit_2.setMaximumSize(QtCore.QSize(24, 24))
        self.exit_2.setStyleSheet("background-color:transparent ;\n"
"border:none;")
        self.exit_2.setObjectName("exit_2")
        self.line = QtWidgets.QFrame(MUSIC_PL)
        self.line.setGeometry(QtCore.QRect(0, 24, 541, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(MUSIC_PL)
        self.label_2.setGeometry(QtCore.QRect(1, 237, 36, 18))
        self.label_2.setObjectName("label_2")
        self.file = QtWidgets.QToolButton(MUSIC_PL)
        self.file.setGeometry(QtCore.QRect(44, 231, 30, 29))
        self.file.setStyleSheet("background-color:transparent;")
        self.file.setIcon(icon2)
        self.file.setObjectName("file")
        self.label_12.raise_()
        self.stop.raise_()
        self.graphicsView.raise_()
        self.listWidget.raise_()
        self.label_2.raise_()
        self.file.raise_()
        self.label.raise_()
        self.dir.raise_()
        self.background.raise_()
        self.line.raise_()

        self.retranslateUi(MUSIC_PL)
        QtCore.QMetaObject.connectSlotsByName(MUSIC_PL)

    def retranslateUi(self, MUSIC_PL):
        _translate = QtCore.QCoreApplication.translate
        MUSIC_PL.setWindowTitle(_translate("MUSIC_PL", "MUSIC"))
        self.stop.setText(_translate("MUSIC_PL", "..."))
        self.dir.setText(_translate("MUSIC_PL", "..."))
        self.label.setText(_translate("MUSIC_PL", "dir"))
        self.exit.setText(_translate("MUSIC_PL", "❌"))
        self.exit.setShortcut(_translate("MUSIC_PL", "Esc"))
        self.exit_2.setText(_translate("MUSIC_PL", "➖"))
        self.exit_2.setShortcut(_translate("MUSIC_PL", "Esc"))
        self.label_2.setText(_translate("MUSIC_PL", "file"))
        self.file.setText(_translate("MUSIC_PL", "..."))
import res_rc
