# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\Video.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1234, 819)
        font = QtGui.QFont()
        font.setPointSize(5)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/video_ico.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.widget = QVideoWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 40, 1211, 641))
        self.widget.setObjectName("widget")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(0, 710, 1231, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lab_duration = QtWidgets.QLabel(Dialog)
        self.lab_duration.setGeometry(QtCore.QRect(1240, 710, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lab_duration.setFont(font)
        self.lab_duration.setText("")
        self.lab_duration.setObjectName("lab_duration")
        self.stop = QtWidgets.QPushButton(Dialog)
        self.stop.setGeometry(QtCore.QRect(580, 750, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.stop.setFont(font)
        self.stop.setStyleSheet("background-color:transparent;")
        self.stop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/windows/play_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon1)
        self.stop.setIconSize(QtCore.QSize(40, 43))
        self.stop.setObjectName("stop")
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(0, 0, 1341, 871))
        self.background.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.228856 rgba(37, 40, 41, 255), stop:0.512438 rgba(0, 0, 0, 255), stop:0.766169 rgba(0, 0, 0, 255), stop:0.9801 rgba(27, 27, 27, 255));")
        self.background.setText("")
        self.background.setObjectName("background")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(1130, 10, 91, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.WindowsTitle = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.WindowsTitle.setContentsMargins(0, 0, 0, 0)
        self.WindowsTitle.setObjectName("WindowsTitle")
        self.small = QtWidgets.QPushButton(self.layoutWidget)
        self.small.setMinimumSize(QtCore.QSize(24, 24))
        self.small.setMaximumSize(QtCore.QSize(24, 24))
        self.small.setStyleSheet("border-radius:12;\n"
"background-color: yellow;")
        self.small.setText("")
        self.small.setObjectName("small")
        self.WindowsTitle.addWidget(self.small)
        self.Max = QtWidgets.QPushButton(self.layoutWidget)
        self.Max.setMinimumSize(QtCore.QSize(24, 24))
        self.Max.setMaximumSize(QtCore.QSize(24, 24))
        self.Max.setStyleSheet("border-radius:12;\n"
"background-color: green;")
        self.Max.setText("")
        self.Max.setObjectName("Max")
        self.WindowsTitle.addWidget(self.Max)
        self.exit = QtWidgets.QPushButton(self.layoutWidget)
        self.exit.setMinimumSize(QtCore.QSize(24, 24))
        self.exit.setMaximumSize(QtCore.QSize(24, 24))
        self.exit.setStyleSheet("border-radius:12;\n"
"background-color: red;")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.WindowsTitle.addWidget(self.exit)
        self.background.raise_()
        self.widget.raise_()
        self.horizontalSlider.raise_()
        self.stop.raise_()
        self.lab_duration.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Video"))
        self.exit.setShortcut(_translate("Dialog", "Esc"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
import res_rc
